# Function to get the icon path based on resource type
import os

# Compute absolute path to the icons directory (project root / icons)
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ICONS_DIR = os.path.join(_PROJECT_ROOT, "icons")


def _abs_icon(relative_path):
    """Convert a relative icon path like 'icons/foo.png' to an absolute path."""
    filename = os.path.basename(relative_path)
    return os.path.join(ICONS_DIR, filename)


def get_icon(resource_type):
    icons = {
        "Subscriptions": "icons/Subscriptions.png",
        "ResourceGroups": "icons/ResourceGroups.png",
        "Subnets": "icons/subnets.png",
        "Microsoft.Authorization/roleAssignments": "icons/rbac-built-in-roles.png",
        "Microsoft.ApiManagement/service": "icons/API-Management-Services.png",
        "Microsoft.AppConfiguration/configurationStores": "icons/App-configuration.png",
        "Microsoft.Automation/automationAccounts": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/certificates": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/compilationjobs": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/configurations": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/connectionTypes": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/connections": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/credentials": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/jobSchedules": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/jobs": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/modules": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/nodeConfigurations": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/python2Packages": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/runbooks": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/schedules": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/softwareUpdateConfigurations": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/sourceControls": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/sourceControls/sourceControlSyncJobs": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/variables": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/watchers": "icons/Automation-Accounts.png",
        "Microsoft.Automation/automationAccounts/webhooks": "icons/Automation-Accounts.png",
        "Microsoft.Cache/Redis": "icons/Cache-Redis.png",
        "Microsoft.Cdn/profiles": "icons/CDN-Profiles.png",
        "Microsoft.Compute/virtualMachines": "icons/Virtual-Machine.png",
        "Microsoft.Compute/virtualMachineScaleSets": "icons/VM-Scale-Sets.png",
        "Microsoft.Compute/virtualMachines/extensions": "icons/extensions.png",
        "Microsoft.Compute/availabilitySets": "icons/Availability-Sets.png",
        "Microsoft.Compute/disks": "icons/Disks.png",
        "Microsoft.Compute/sshPublicKeys": "icons/ssh-keys.png",
        "Microsoft.Compute/snapshots": "icons/Disks-Snapshots.png",
        "Microsoft.ContainerInstance/containerGroups": "icons/Container-Instances.png",
        "Microsoft.ContainerRegistry/registries": "icons/Container-Registries.png",
        "Microsoft.DataShare/accounts": "icons/Data-Shares.png",
        "Microsoft.DocumentDB/databaseAccounts": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/databases": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/databases/collections": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/databases/containers": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/databases/graphs": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/keyspaces": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/apis/tables": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/cassandraKeyspaces": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/gremlinDatabases": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/storedProcedures": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/triggers": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/userDefinedFunctions": "icons/Azure-Cosmos-DB.png",
        "Microsoft.DocumentDB/databaseAccounts/tables": "icons/Azure-Cosmos-DB.png",
        "Microsoft.EventGrid/topics": "icons/Event-Grid-Topics.png",
        "microsoft.insights/components": "icons/Application-Insights.png",
        "microsoft.insights/components/query": "icons/Application-Insights.png",
        "microsoft.insights/components/metadata": "icons/Application-Insights.png",
        "microsoft.insights/components/metrics": "icons/Application-Insights.png",
        "microsoft.insights/components/events": "icons/Application-Insights.png",
        "microsoft.insights/webtests": "icons/Application-Insights.png",
        "microsoft.insights/webtests/getTestResultFile": "icons/Application-Insights.png",
        "microsoft.insights/components/pricingPlans": "icons/Application-Insights.png",
        "microsoft.insights/migrateToNewPricingModel": "icons/Application-Insights.png",
        "microsoft.insights/rollbackToLegacyPricingModel": "icons/Application-Insights.png",
        "microsoft.insights/listMigrationdate": "icons/Application-Insights.png",
        "microsoft.insights/logprofiles": "icons/Application-Insights.png",
        "microsoft.insights/migratealertrules": "icons/Application-Insights.png",
        "microsoft.insights/alertrules": "icons/alerts.png",
        "microsoft.insights/autoscalesettings": "icons/Application-Insights.png",
        "microsoft.insights/eventtypes": "icons/Application-Insights.png",
        "microsoft.insights/locations": "icons/Application-Insights.png",
        "microsoft.insights/locations/operationResults": "icons/Application-Insights.png",
        "microsoft.insights/vmInsightsOnboardingStatuses": "icons/Application-Insights.png",
        "microsoft.insights/operations": "icons/Application-Insights.png",
        "microsoft.insights/diagnosticSettings": "icons/Application-Insights.png",
        "microsoft.insights/diagnosticSettingsCategories": "icons/Application-Insights.png",
        "microsoft.insights/extendedDiagnosticSettings": "icons/Application-Insights.png",
        "microsoft.insights/metricDefinitions": "icons/Application-Insights.png",
        "microsoft.insights/logDefinitions": "icons/Application-Insights.png",
        "microsoft.insights/eventCategories": "icons/Application-Insights.png",
        "microsoft.insights/metrics": "icons/Application-Insights.png",
        "microsoft.insights/metricbatch": "icons/Application-Insights.png",
        "microsoft.insights/metricNamespaces": "icons/Application-Insights.png",
        "microsoft.insights/actionGroups": "icons/Action-Groups.png",
        "microsoft.Insights/activityLogAlerts": "icons/alerts.png",
        "microsoft.insights/baseline": "icons/Application-Insights.png",
        "microsoft.insights/metricbaselines": "icons/Application-Insights.png",
        "microsoft.insights/calculatebaseline": "icons/Application-Insights.png",
        "microsoft.insights/workbooks": "icons/Application-Insights.png",
        "microsoft.insights/workbooktemplates": "icons/Application-Insights.png",
        "microsoft.insights/myWorkbooks": "icons/Application-Insights.png",
        "microsoft.insights/logs": "icons/Application-Insights.png",
        "microsoft.insights/transactions": "icons/Application-Insights.png",
        "microsoft.insights/topology": "icons/Application-Insights.png",
        "microsoft.insights/generateLiveToken": "icons/Application-Insights.png",
        "microsoft.Insights/dataCollectionRules": "icons/dataCollectionRules.png",
        "microsoft.insights/dataCollectionRuleAssociations": "icons/Application-Insights.png",
        "microsoft.insights/privateLinkScopes": "icons/Application-Insights.png",
        "microsoft.insights/privateLinkScopes/privateEndpointConnections": "icons/Application-Insights.png",
        "microsoft.insights/privateLinkScopes/privateEndpointConnectionProxies": "icons/Application-Insights.png",
        "microsoft.insights/privateLinkScopes/scopedResources": "icons/Application-Insights.png",
        "microsoft.insights/components/linkedstorageaccounts": "icons/Application-Insights.png",
        "microsoft.insights/privateLinkScopeOperationStatuses": "icons/Application-Insights.png",
        "Microsoft.Insights/scheduledQueryRules": "icons/alerts.png",
        "Microsoft.Insights/metricAlerts": "icons/alerts.png",
        "Microsoft.KeyVault/vaults": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/vaults/secrets": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/vaults/accessPolicies": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/operations": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/checkNameAvailability": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/deletedVaults": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/locations": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/locations/deletedVaults": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/locations/deleteVirtualNetworkOrSubnets": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/locations/operationResults": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/vaults/eventGridFilters": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/managedHSMs": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/deletedManagedHSMs": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/locations/deletedManagedHSMs": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/vaults/keys": "icons/Key-Vaults.png",
        "Microsoft.KeyVault/vaults/keys/versions": "icons/Key-Vaults.png",
        "Microsoft.ManagedIdentity/userAssignedIdentities": "icons/managedidentities.png",
        "Microsoft.ContainerService/managedClusters": "icons/Kubernetes-Services.png",
        "microsoft.alertsmanagement/smartDetectorAlertRules": "icons/alerts.png",
        "Microsoft.Media/mediaServices": "icons/Media.png",
        "Microsoft.Network/ApplicationGateways": "icons/Application-Gateways.png",
        "Microsoft.Network/frontdoors": "icons/Front-Doors.png",
        "Microsoft.Network/azureFirewalls": "icons/Firewalls.png",
        "Microsoft.Network/firewallPolicies": "icons/FirewallPolicy.png",
        "Microsoft.Network/loadBalancers": "icons/Load-Balancers.png",
        "Microsoft.Network/networkInterfaces": "icons/Network-Interfaces.png",
        "Microsoft.Network/networkSecurityGroups": "icons/Network-Security-Groups.png",
        "Microsoft.Network/networkSecurityGroups/securityRules": "icons/Network-Security-Groups.png",
        "Microsoft.Network/publicIPAddresses": "icons/Public-IP-Addresses.png",
        "Microsoft.Network/publicIPPrefixes": "icons/Public-IP-Addresses.png",
        "Microsoft.Network/routeTables": "icons/Route-Tables.png",
        "Microsoft.Network/routeTables/routes": "icons/Route-Tables.png",
        "Microsoft.Network/trafficManagerProfiles": "icons/Traffic-Manager-Profiles.png",
        "Microsoft.Network/virtualNetworkGateways": "icons/Virtual-Network-Gateways.png",
        "Microsoft.Network/privateEndpoints": "icons/privateendpoint.png",
        "Microsoft.Network/virtualNetworks": "icons/Virtual-Networks.png",
        "Microsoft.Network/privateDnsZones": "icons/DNS-Zones.png",
        "Microsoft.Network/dnsZones": "icons/DNS-Zones.png",
        "Microsoft.Network/bastionHosts": "icons/Azure-Bastion.png",
        "Microsoft.OperationsManagement/solutions": "icons/solutions.png",
        "Microsoft.ServiceFabric/clusters": "icons/Service-Fabric-Clusters.png",
        "Microsoft.Sql/instancePools": "icons/Instance-Pools.png",
        "Microsoft.Sql/locations/instanceFailoverGroups": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/administrators": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/databases": "icons/SQL-Database.png",
        "Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/databases/schemas/tables/columns/sensitivityLabels": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/databases/securityAlertPolicies": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments/rules/baselines": "icons/SQL-Managed-Instance.png",
        "Microsoft.Sql/managedInstances/encryptionProtector": "icons/SQL-Server.png",
        "Microsoft.Sql/managedInstances/keys": "icons/SQL-Server.png",
        "Microsoft.Sql/managedInstances/restorableDroppedDatabases/backupShortTermRetentionPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/managedInstances/securityAlertPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/managedInstances/vulnerabilityAssessments": "icons/SQL-Server.png",
        "Microsoft.Sql/servers": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/administrators": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/auditingSettings": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/backupLongTermRetentionVaults": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/communicationLinks": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/connectionPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/auditingSettings": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/connectionPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/dataMaskingPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/dataMaskingPolicies/rules": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/extendedAuditingSettings": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/extensions": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/geoBackupPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/schemas/tables/columns/sensitivityLabels": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/securityAlertPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/syncGroups": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/syncGroups/syncMembers": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/transparentDataEncryption": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/vulnerabilityAssessments": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/databases/vulnerabilityAssessments/rules/baselines": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/disasterRecoveryConfiguration": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/dnsAliases": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/elasticPools": "icons/SQL-Elastic-Pools.png",
        "Microsoft.Sql/servers/encryptionProtector": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/extendedAuditingSettings": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/failoverGroups": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/firewallRules": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents/credentials": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents/jobs": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents/jobs/executions": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents/jobs/steps": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/jobAgents/targetGroups": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/keys": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/privateEndpointConnections": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/securityAlertPolicies": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/syncAgents": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/virtualNetworkRules": "icons/SQL-Server.png",
        "Microsoft.Sql/servers/vulnerabilityAssessments": "icons/SQL-Server.png",
        "Microsoft.Storage/storageAccounts": "icons/Storage-Accounts.png",
        "Microsoft.Storage/storageAccounts/fileServices": "icons/Storage-Azure-Files.png",
        "Microsoft.Storage/storageAccounts/blobServices": "icons/Blob-Block.png",
        "Microsoft.Storage/storageAccounts/queueServices": "icons/Storage-Queue.png",
        "Microsoft.Storage/storageAccounts/tableServices": "icons/Table.png",
        "Microsoft.OperationalInsights/workspaces": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/scopedPrivateLinkProxies": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/query": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/metadata": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/dataSources": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/linkedStorageAccounts": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/Tables": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/linkedServices": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/deletedWorkspaces": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.OperationalInsights/workspaces/dataExport": "icons/Log-Analytics-Workspaces.png",
        "Microsoft.DataFactory/dataFactories": "icons/Data-Factory.png",
        "Microsoft.DataFactory/factories": "icons/Data-Factory.png",
        "Microsoft.DataFactory/factories/integrationRuntimes": "icons/Data-Factory.png",
        "Microsoft.DataFactory/dataFactories/diagnosticSettings": "icons/Data-Factory.png",
        "Microsoft.DataFactory/dataFactories/metricDefinitions": "icons/Data-Factory.png",
        "Microsoft.DataFactory/checkDataFactoryNameAvailability": "icons/Data-Factory.png",
        "Microsoft.DataFactory/checkAzureDataFactoryNameAvailability": "icons/Data-Factory.png",
        "Microsoft.DataFactory/dataFactorySchema": "icons/Data-Factory.png",
        "Microsoft.DataFactory/operations": "icons/Data-Factory.png",
        "Microsoft.DataFactory/locations": "icons/Data-Factory.png",
        "Microsoft.DataFactory/locations/configureFactoryRepo": "icons/Data-Factory.png",
        "Microsoft.DataFactory/locations/getFeatureValue": "icons/Data-Factory.png",
        "Microsoft.Web/connections": "icons/Connections.png",
        "Microsoft.Web/serverfarms": "icons/App-Service-Plans.png",
        "Microsoft.Databricks/workspaces": "icons/databricks.png",
        "Microsoft.Databricks/workspaces/virtualNetworkPeerings": "icons/databricks.png",
        "Microsoft.Databricks/workspaces/dbWorkspaces": "icons/databricks.png",
        "Microsoft.Databricks/operations": "icons/databricks.png",
        "Microsoft.Databricks/locations": "icons/databricks.png",
        "Microsoft.Databricks/locations/operationstatuses": "icons/databricks.png",
        "Microsoft.Databricks/locations/getNetworkPolicies": "icons/databricks.png",
        "Microsoft.DataLakeAnalytics/accounts": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/accounts/dataLakeStoreAccounts": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/accounts/storageAccounts": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/accounts/storageAccounts/containers": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/accounts/storageAccounts/containers/listSasTokens": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/locations": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/locations/operationresults": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/locations/checkNameAvailability": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/locations/capability": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/locations/usages": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.DataLakeAnalytics/operations": "icons/Data-Lake-Storage-Gen1.png",
        "Microsoft.EventHub/namespaces": "icons/Event-Hubs.png",
        "Microsoft.EventHub/clusters": "icons/Event-Hub-Clusters.png",
        "Microsoft.EventHub/namespaces/authorizationrules": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/networkrulesets": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/eventhubs": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/eventhubs/authorizationrules": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/eventhubs/consumergroups": "icons/Event-Hubs.png",
        "Microsoft.EventHub/checkNamespaceAvailability": "icons/Event-Hubs.png",
        "Microsoft.EventHub/checkNameAvailability": "icons/Event-Hubs.png",
        "Microsoft.EventHub/sku": "icons/Event-Hubs.png",
        "Microsoft.EventHub/operations": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/disasterrecoveryconfigs": "icons/Event-Hubs.png",
        "Microsoft.EventHub/namespaces/disasterrecoveryconfigs/checkNameAvailability": "icons/Event-Hubs.png",
        "Microsoft.EventHub/locations": "icons/Event-Hubs.png",
        "Microsoft.EventHub/locations/deleteVirtualNetworkOrSubnets": "icons/Event-Hubs.png",
        "Microsoft.EventHub/availableClusterRegions": "icons/Event-Hubs.png",
        "Microsoft.EventGrid/namespaces": "icons/Event-Grid-Namespace.png",
        "Microsoft.Web/sites": "icons/Function-Apps.png",
        "config": "icons/app-configuration.png",
        "resources": "icons/All-Resources.png",
        "Microsoft.Synapse/workspaces": "icons/Azure-Synapse-Analytics.png",
        "Microsoft.Portal/dashboards": "icons/Dashboard.png",
        "Microsoft.Fabric/capacities": "icons/Fabric-capacities.png",
        "Microsoft.Purview/accounts": "icons/purview.png",
        # Child resources that were missing
        "Microsoft.Insights/metricalerts": "icons/alerts.png",
        "Microsoft.Insights/scheduledqueryrules": "icons/alerts.png",
        "Microsoft.Network/privateDnsZones/virtualNetworkLinks": "icons/DNS-Zones.png",
        "Microsoft.Network/privateEndpoints/privateDnsZoneGroups": "icons/privateendpoint.png",
        "Microsoft.Storage/storageAccounts/blobServices/containers": "icons/Blob-Block.png",
        "Microsoft.Storage/storageAccounts/fileServices/shares": "icons/Storage-Azure-Files.png",
        "Microsoft.Storage/storageAccounts/queueServices/queues": "icons/Storage-Queue.png",
        "Microsoft.Storage/storageAccounts/tableServices/tables": "icons/Table.png",
        "Microsoft.Web/sites/config": "icons/app-configuration.png",
        "Microsoft.ContainerService/managedClusters": "icons/Kubernetes-Services.png",
        "Microsoft.Network/virtualNetworks/subnets": "icons/subnets.png",
        "Microsoft.Portal/dashboards": "icons/Dashboard.png",
        # Add more resource types and their corresponding icons here
    }
    # Convert the keys of the icons dictionary to lowercase
    icons_lower = {k.lower(): v for k, v in icons.items()}

    # Convert the resource_type to lowercase
    resource_type_lower = resource_type.lower()

    # Try exact match first
    if resource_type_lower in icons_lower:
        return _abs_icon(icons_lower[resource_type_lower])

    # For child resources (e.g., Microsoft.Network/privateEndpoints/xxx), try parent type
    # Split by '/' and progressively try parent types
    parts = resource_type_lower.split("/")
    for i in range(len(parts) - 1, 0, -1):
        parent_type = "/".join(parts[:i])
        if parent_type in icons_lower:
            return _abs_icon(icons_lower[parent_type])

    # Return default icon if nothing found
    return _abs_icon("icons/resources.png")
